{% set name = "jax-jumpy" %}
{% set version = "1.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 195fb955cc4c2b7f0b1453e3cb1fb1c414a51a407ffac7a51e69a73cb30d59ad

build:
  number: 0
  skip: True  # [py<37]
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - setuptools >=61.0.0
    - pip
    - python
    - wheel
  run:
    - numpy >=1.18.0
    - python
  run_constrained:
    - jax >=0.3.24
    - jaxlib >=0.3.24

test:
  imports:
    - jumpy
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/Farama-Foundation/Jumpy
  summary: Common backend for JAX or numpy.
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  description: |
    Jumpy is a common backend for JAX or numpy.
  doc_url: https://github.com/Farama-Foundation/Jumpy
  dev_url: https://github.com/Farama-Foundation/Jumpy

extra:
  recipe-maintainers:
    - thewchan
